name: Process New Event

on:
  push:
    branches:
      - main
    # paths:
    # - 'posts/new-event*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Important for "Create Pull Request" step

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: cd ai && yarn install --network-timeout 1000000

      - name: Build and Process new event
        run: cd ai && yarn start
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Set up Git user
        run: |
          git config --local user.email "niteshbalusu@icloud.com"
          git config --local user.name "Nitesh Balusu"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Add new summary'
          commit-message: Add summary
          body: 'This pull request adds a new summary.'
          branch: 'new-summary'
